### ISSUE TITLE
add color tokens for dark mode

### ISSUE THREAD

**Issue by yoonbuck** [design-awareness/design-awareness-app#21]
https://github.com/design-awareness/design-awareness-app/blob/main/src/styles/colors.scss
(don't worry about activity colors for now)

**Comment by khajor** [comment]
Not sure what to do about the yellow  active-bar color...? Could just leave it which isn't the worst

**Comment by yoonbuck** [comment]
sure, let's leave it for now. We can pick out another color for this later if it's bad :)
