### ISSUE TITLE
Activity name inputs don't use dark mode

### ISSUE THREAD

**Issue by yoonbuck** [design-awareness/design-awareness-app#34]
When creating a new design activity set, the text inputs for activity names don't change in dark mode.

**Comment by khajor** [comment]
Made a temporary fix by manually inserting input field BG and text colors in ActivityEditor.svelte - This is probably not best practice but works! Is there a better way/ place to look for this bug?

**Comment by yoonbuck** [comment]
This looks good to me — we're not using any of the pre-styled components there so it seems fine to do it manually.

Closed in 219e371d81fa4d7db366bb4bcec9676b1b048ed8
